/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _platformmode_h_
#define _platformmode_h_
//---------------------------------------------------------------------------------
extern const unsigned char platformmode[];
extern const int platformmode_size;
//---------------------------------------------------------------------------------
#endif //_platformmode_h_
//---------------------------------------------------------------------------------
