/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bombsound_h_
#define _bombsound_h_
//---------------------------------------------------------------------------------
extern const unsigned char bombsound[];
extern const int bombsound_size;
//---------------------------------------------------------------------------------
#endif //_bombsound_h_
//---------------------------------------------------------------------------------
