/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _explosion_h_
#define _explosion_h_
//---------------------------------------------------------------------------------
extern const unsigned char explosion[];
extern const int explosion_size;
//---------------------------------------------------------------------------------
#endif //_explosion_h_
//---------------------------------------------------------------------------------
