/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Chalkboard32_h_
#define _Chalkboard32_h_
//---------------------------------------------------------------------------------
extern const unsigned char Chalkboard32[];
extern const int Chalkboard32_size;
//---------------------------------------------------------------------------------
#endif //_Chalkboard32_h_
//---------------------------------------------------------------------------------
