/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Chalkboard24_h_
#define _Chalkboard24_h_
//---------------------------------------------------------------------------------
extern const unsigned char Chalkboard24[];
extern const int Chalkboard24_size;
//---------------------------------------------------------------------------------
#endif //_Chalkboard24_h_
//---------------------------------------------------------------------------------
