/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Chalkboard96_h_
#define _Chalkboard96_h_
//---------------------------------------------------------------------------------
extern const unsigned char Chalkboard96[];
extern const int Chalkboard96_size;
//---------------------------------------------------------------------------------
#endif //_Chalkboard96_h_
//---------------------------------------------------------------------------------
