/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_player_001_h_
#define _MyLittleBall_player_001_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_player_001[];
extern const int MyLittleBall_player_001_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_player_001_h_
//---------------------------------------------------------------------------------
