/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_ingame_bg_h_
#define _MyLittleBall_ingame_bg_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_ingame_bg[];
extern const int MyLittleBall_ingame_bg_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_ingame_bg_h_
//---------------------------------------------------------------------------------
