/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_platform_0001_h_
#define _MyLittleBall_platform_0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_platform_0001[];
extern const int MyLittleBall_platform_0001_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_platform_0001_h_
//---------------------------------------------------------------------------------
