/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_platform_0004_h_
#define _MyLittleBall_platform_0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_platform_0004[];
extern const int MyLittleBall_platform_0004_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_platform_0004_h_
//---------------------------------------------------------------------------------
