/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_towel_h_
#define _MyLittleBall_towel_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_towel[];
extern const int MyLittleBall_towel_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_towel_h_
//---------------------------------------------------------------------------------
