/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _MyLittleBall_title_message_h_
#define _MyLittleBall_title_message_h_
//---------------------------------------------------------------------------------
extern const unsigned char MyLittleBall_title_message[];
extern const int MyLittleBall_title_message_size;
//---------------------------------------------------------------------------------
#endif //_MyLittleBall_title_message_h_
//---------------------------------------------------------------------------------
